[2022-03-13 15:19:32,633] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: example_dag_decorator.send_email manual__2022-03-13T15:19:24.662229+00:00 [queued]>
[2022-03-13 15:19:32,644] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: example_dag_decorator.send_email manual__2022-03-13T15:19:24.662229+00:00 [queued]>
[2022-03-13 15:19:32,644] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-13 15:19:32,644] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-13 15:19:32,644] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-13 15:19:32,702] {taskinstance.py:1264} INFO - Executing <Task(EmailOperator): send_email> on 2022-03-13 15:19:24.662229+00:00
[2022-03-13 15:19:32,705] {standard_task_runner.py:52} INFO - Started process 1107 to run task
[2022-03-13 15:19:32,709] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'example_dag_decorator', 'send_email', 'manual__2022-03-13T15:19:24.662229+00:00', '--job-id', '12', '--raw', '--subdir', '/home/***/.local/lib/python3.7/site-packages/***/example_dags/example_dag_decorator.py', '--cfg-path', '/tmp/tmpsga5u4xu', '--error-file', '/tmp/tmpse5m0wjw']
[2022-03-13 15:19:32,709] {standard_task_runner.py:77} INFO - Job 12: Subtask send_email
[2022-03-13 15:19:32,840] {logging_mixin.py:109} INFO - Running <TaskInstance: example_dag_decorator.send_email manual__2022-03-13T15:19:24.662229+00:00 [running]> on host 33f4149e0bde
[2022-03-13 15:19:33,798] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=example_dag_decorator
AIRFLOW_CTX_TASK_ID=send_email
AIRFLOW_CTX_EXECUTION_DATE=2022-03-13T15:19:24.662229+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-13T15:19:24.662229+00:00
[2022-03-13 15:19:33,806] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:108: PendingDeprecationWarning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2022-03-13 15:19:33,806] {configuration.py:381} WARNING - section/key [smtp/smtp_user] not found in config
[2022-03-13 15:19:33,806] {email.py:214} INFO - Email alerting: attempt 1
[2022-03-13 15:19:33,807] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/email.py", line 88, in execute
    conn_id=self.conn_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 69, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 108, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 216, in send_mime_email
    conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 250, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2022-03-13 15:19:33,816] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=example_dag_decorator, task_id=send_email, execution_date=20220313T151924, start_date=20220313T151932, end_date=20220313T151933
[2022-03-13 15:19:33,975] {standard_task_runner.py:92} ERROR - Failed to execute job 12 for task send_email
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/email.py", line 88, in execute
    conn_id=self.conn_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 69, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 108, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 216, in send_mime_email
    conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 250, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2022-03-13 15:19:34,003] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-13 15:19:34,111] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
